### ISSUE TITLE
Fails when expected result should be a Float

### ISSUE THREAD

**Issue by ayazhafiz** [aunyks/metadelta-js#2]
We expect the area under the curve x^2 on [1,3] to be 27/3 - 1/3 = 26/3 ~= 8.667.
Performing this operation with metadelta, however, leads to an integer answer of 8.
```
metadelta.areaUnder('x^2', { start: 1, finish: 3})
8
```
This problem seems to be caused by the parsing of the lower limit as an integer rather than as a float on [line 59 of calculus.js](https://github.com/metadelta/metadelta/blob/master/src/calculus.js#L59).

A similar problem occurs when we attempt to find non-integer zeroes of a curve. Given the function x^2-3, we expect the zeroes [-sqrt(3), sqrt(3)] ~= [-1.73, 1.73], but are instead returned with [3, -3]. This too appears to be because of [integer parsing](https://github.com/metadelta/metadelta/blob/master/src/algebra.js#L38).

Is there a reason that strings are parsed as integers rather than floats, or can this be fixed?

**Comment by aunyks** [comment]
Good catch! I'll get on this soon!
